version: '3'
services:

  web:
    container_name: vote-web
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn vote.wsgi:application --bind 0.0.0.0:8888
    environment:
      DJANGO_SETTINGS_MODULE: vote.settings.prod
    env_file:
      - .env
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    expose:
      - 8888
    entrypoint:
      - sh
      - config/docker/entrypoint.prod.sh

  nginx:
    container_name: vote-nginx
    build: ./config/nginx
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static:
  media: